var questions = ['the average frequency of sex for couples is about eight times a month. How many times a month do you feel is ideal? ',
'where do you see us in the next 10 years?',
'if there’s one thing you’d want to change about me, what is it?',
'if you were to choose a chain restaurant to describe me which one would you choose and why?',
'how many sexual partners have you had?',
'did you ever fake an orgasm?',
'what\'s your favorite sex position?',
'what\'s your least favorite sex position?',
'who or what do you most picture when you are masturbating?',
'when was the last time you lied to me and why?',
'what do you find most annoying about me?',
'have you ever had a threesome? Would you?',
'when was the last time you masturbated?',
'are you happy with our current relationship?',
'if I was never born -- what do you think your life would be like?',
'have you ever disliked someone I dated?',
'what were your first impressions of me?',
'do you send nude images to people you\'re dating?',
'have you ever stolen from me?',
'what\'s something I do that embarasses you?',
'what do we have in common that you like the most?',
'how many times do you masturbate a week?',
'have you ever masturbated in a public place?',
'have you ever stolen anything?',
'would you still love your significant other/crush if he or she gained 100 pounds?',
'how often do you take selfies?',
'who was your first crush?',
'how long have you gone without showering?',
'what celebrity do you have a crush on?',
'which physical feature do you feel most self-conscious about?',
'what tv show are you embarrassed about watching?',
'when you are trying to impress people what personality trait do you hide?',
'who in this room would be the worst to be trapped in an elevator with? ',
'what are you afraid of? ',
'what talent do you have that is embarrassing to share?',
'have you ever had a one night stand?',
'what fear keeps you up at night?',
'what do you do when you are alone in your room?',
'what haven’t you done sexually that you still dream about doing?',
'what was the last intimate moment you ruined and how did you ruin it?',
'describe the grossest bodily function you’ve ever had',
'take a body shot off me. To get out of it take two shots.',
'exchange shirts with me',
'make up a rap about me',
'name a mutual friend you’d make out with',
'I dare you to do 10 pushups',
'let me slap you across the face',
'describe the craziest sexual encounter you’ve ever had',
'what’s the most disgusting habit you have?',
'I dare you to kiss me on my mouth. To get out of it (for either of you) take a shot.',
'do an interpretive dance of your lamest sexual experience',
'demonstrate your preferred blowjob technique on a banana',
'do you have any irrational fears?',
'do you have any fetishes?',
'when was the last time you had sex?',
'remove (any) item of clothing',
'give me a foot massage',
//'text your mom and tell her you love and miss her',
'if you were rescuing everyone here from a burning building but HAD to leave someone behind, who would it be?',
'what prejudices do you have?',
'who is the worst dressed here?',
'suck your toe. If you can’t, you have to suck mine',
'have you ever had a crush on a teacher? Who?',
'when was the last time you peed yourself?',
'what would you say about my personality? Rate it 1-10 and describe me',
'would you rather kiss the person on your right or your left? Do it',
'what one object are you most embarrassed about owning?',
'describe the last time you publicly embarrassed yourself',
'name every crush you’ve ever had',
'what’s one thing that almost never fails to turn you on?',
'would you ever consider a completely sexless relationship/marriage?',
'do you consider yourself to be a good person?',
'how far have you gone on the first date?',
'have you ever been with anyone of the same sex?',
'do you believe in God or a higher power?',
'what worries you most about your future?',
'what impact do you want to leave on the world?',
'describe your biggest turn-offs',
'name something you’ve done recently that you aren’t proud of',
'what’s one thing you pretend to understand that you really don’t get?',
'was there a time you should’ve spoken up and you didn’t?',
'what mistakes do you make over and over again?',
'what do you do when people don’t like you?',
'name a role model of yours and why?',
'do you think any kind of afterlife exists?',
'would you kill an innocent person if you thought it might mean saving a dozen other people?',
'what’s the most money you’ve ever given away?',
'what’s the biggest personal change you’ve ever made?',
'what’s the stupidest thing you’ve ever done?',
'when and where would you go in a time travel machine? Would you stay?',
'what do you most regret and wish you could re-do?',
'what\'s the absolute best vacation you can imagine?',
'boxers or briefs?',
'coke or pepsi?',
'what do you imagine sex is like for the opposite sex?',
'if you had to pick a new first name, what would it be?',
'would you rather be feared or loved?',
'tell us the story of a scar you have',
'are you superstitious about anything?',
'on a scale of 1 to 10, how controlling a person are you? Explain',
'is it more important to you to look good or feel good?',
'what’s the meanest thing you’ve ever done out of revenge?',
'what’s one word in my vocabulary that I use excessively?',
'would you lie under oath for me?',
'what’s the grossest word you can think of?',
'who’s the biggest bitch in the room?',
'what is your least favorite thing about me?',
'carry me around the room once.  To get out of it (for either of you) take a shot.',
'who do you think has the best hair in the room?',
'how many people have you made out with?',
'if you had to marry someone tomorrow, who would you pick and why?',
'what’s your middle name?',
'what would you say are my best physical and emotional attributes?',
'when was the last time you cried?',
'have you ever been in a brawl?',
'what do you want to be when you grow up?',
'have you ever been skinny dipping?',
'have you ever fantasized about anyone in this room? Who?',
'describe your worst date ever',
'what\'s the most embarrassing thing you have done while drunk?',
'have you ever smoked weed?',
'if you were stranded on an island, which person in this room would you NOT want to be stranded with?',
'what happened in your last nightmare?',
'do you own any sex toys?',
'describe your relationship with porn',
'wear your underwear on your head. ',
'lick my ear',
'give me a massage.  To get out of it (for either of you) take a shot.',
'remove an article of my clothing using only your teeth. To get out of it (for either of you) take a shot.',
'do you think I have good taste in music?',
'have you ever been attracted to a partner of mine?',
'have you ever had a sex dream about me? What happened?',
'sit on my lap and stare into my eyes intimately for one full minute or take a shot.',
'what would it take for us to have sex?',
'have you ever caught me masturbating or having sex? What did/would you do?',
'who would you be most embarrassed to introduce me to? Why?',
'if someone offered you one million dollars to never talk to me again, would you?',
'how would you describe me to someone who’s never met me?',
'do you love me? If yes, say it and take a shot.',
'what are some things I do to let you know I’m mad without me actually saying anything?',
'have I ever told you a secret that you’ve gone on to tell someone else? Which one?',
'if I killed somebody would you help me cover up?',
'if we were to meet now would we still be best friends?',
'if you had to eat one part of my body what part would it be?',
'when was the moment you knew we were (best) friends?',
'what is your biggest fear?',
'what is your favorite genre of porn?',
'what’s the biggest thing we’ve ever fought about?',
'what would tear our friendship apart?',
'which one of your immediate family members lost their virginity the youngest?',
'which would you rather give up forever, cheese or oral sex?',
'which would you rather give up forever, cheese or chocolate?',
'go around the room and guess how many people each person has slept with?',
'who have you had the best sex with and what made it so great?',
'would you have sex with an ex again and if so, who and why?',
'go around the room and point to the one person you’d marry, have sex with, and kill',
'what’s the most times you’ve masturbated in a day?',
'who here do you think has the best boobs?',
'have you ever given anyone a lapdance?',
'give me a lapdance.',
'have you ever been to a strip club? Which one?',
'would you have sex with the last person you text messaged?',
'when was the last time you talked to an ex?',
'have you taken someone’s virginity?',
'is trust a big issue for you?',
'how many people do you fully trust?',
'do you think you’ll change in the next 3 months?',
'who in this room do you feel most comfortable talking to about anything?',
'describe last time you felt broken?',
'who you miss the most right now?',
'does everyone deserve a second chance?',
'do you believe in love at first sight?',
'who was the last person you danced with?',
'what do you wear to bed?',
'is there a profession you picture your future spouse doing?',
'what’s one thing you should know by now but you secretly don’t?',
'do you consider yourself beautiful?',
'would you ever get plastic surgery?',
'would you get an abortion if you were pregnant?',
'what’s the worst punishment someone could give you?',
'is there anyone in your family you don’t talk to? Why?',
'who in this room are you most jealous of and why?',
'when do you feel most alone?',
'would you go back in time to change your past?',
'do you think the government is truthful?',
'what would I have to do to make you lose all respect for me?',
'have you ever cheated on someone?',
'do you think people are generally good?',
'are you currently happy with your life?',
'what’s the first thing you would grab if there was a fire in your house?',
'if you had 3 wishes right now what would they be? (typical wish rules apply)',
'what age range would you consider hooking up with/dating? (youngest-oldest)',
'if you had to delete one year of your life completely which year would it be?',
'what’s the hardest drug you’ve ever done?',
'how did you lose your virginity?',
'what’s the most hurtful thing anyone’s ever said to you?',
'let me put makeup on you with my eyes closed',
'do an impression of me',
'sing some karaoke',
'turn all of your clothing inside out',
'when did your first dream die?',
'who’s the smartest person in this room?',
'who in this room has the grossest habits?',
'show everyone the last photo in your camera roll',
'what’s one word you want people to use when describing you?',
'what’s the one thing you want to be remembered for?',
'order us pizza',
'what would you do with 15 minutes of fame?',
'do a handstand',
'what’s the best adventure you’ve ever been on?',
'what do you wish you could unsee?',
'name one thing you say you like but you really can’t stand?',
'whose profile do you visit the most on Facebook?',
'when was the last time you did something you knew was wrong?',
'which ex would you give another chance to?',
'how many tattoos do you have and where? If none, do you want any?',
'who was your first kiss? Would you want a do-over?',
'what’s the worst rumor you ever heard about yourself?',
'what’s the worst rumor you ever heard about me?',
'what’s the best compliment you’ve ever received?',
'what do I do that irritates you?',
'what’s the weirdest thing you’ve ever eaten?',
'what’s the worst thing your parents have caught you doing?',
'share a guilty pleasure',
'what was the scariest moment of your life thus far?',
'who did you last dream about?',
'have you ever been in love? How many times?',
'what’s most intriguing about me?',
'take a selfie with me and post it',
'which skills are you most proud of?',
'favorite pet?',
'when are you happiest?',
'last movie that made you cry?',
'twerk',
'read your last text out loud',
'arm wrestle me',
'sit on me until your next turn',
'go around the circle and tell everyone something you find attractive about them',
'get naked',
'take a shot',
'play the uncomfortable game with me',
'sing the alphabet backwards',
'brush your teeth in front of everyone',
'put on someone else\'s bra',
'put ice cubes in your underwear for five minutes',
'draw a face around your belly button',
'touch your nose with your tongue. If you can\'t, touch mine',
'put lipstick on me without using your hands',
'poke someone you don’t know on Facebook',
'put your hands in my pockets for seven turn',
'get down on your knees and pray for the group',
'wear your clothes in reverse order',
];